### PR TITLE
Upgrade nerves templates to match the 1.5 generator

### LINKED ISSUE #38: Generate Nerves 1.5 compatible projects
The nerves project generator should generate projects that are compatible with Nerves 1.5. Basically we need to apply these changes to the template files:

https://hexdocs.pm/nerves/updating-projects.html#updating-from-v1-4-to-v1-5

### PR DESCRIPTION
**Pull request by axelson**
Followed:
* https://hexdocs.pm/nerves/updating-projects.html#updating-from-v1-3-to-v1-4
* https://hexdocs.pm/nerves/updating-projects.html#updating-from-v1-4-to-v1-5
* Compared against the output of a new nerves project

Notes:
* I let the list of targets match the default nerves generator
  * I debated adding a notice that scenic has only been tested with RPI3 but I'm not convinced that this would be the best place for such a notice
* I changed the config file names to match the nerves generator (i.e. instead of `config/config.rpi3.exs` it is just `config/rpi3.exs`. This can be changed back if necessary
* I added `nerves_init_gadget` and toolshed since they are now added by default
* I added `nerves_firmware_ssh` configuration since it is part of the default nerves generator and is very useful for development
* I left the nerves_init_gadget configuration since I figured it wouldn't hurt anything, but I could see an argument for removing it

I've tested this so far in host mode and building a firmware but I haven't tried running the firmware on a device.

TODO:
- [ ] Fix the escaping in `rel/vm.args.eex`

Fixes #38

### CODE REVIEW

**Comment by boydm** [comment]
@axelson @fhunleth I'm still not booting all the way through. Seems stuck on the ft5406 driver.

I'll hook up the uart cable later today and see what else I can learn.

**Comment by axelson** [comment]
@boydm do you think you might be hitting the build/priv error? This PR doesn't bring in those changes since they're not on hex yet.

I just pushed up more changes but they wouldn't affect the error that you're seeing.

If you follow this steps it works for me on my rpi3:
```
mix scenic.new.nerves nnerves
cd nnerves
mix deps.get
mix firmware
rm -rf _build
mix firmware
mix firmware.gen.script
./upload.sh nerves.local
```
(or you could mix firmware.burn of course)

The only change I was testing with was configuring eth0 instead of usb0.

**Comment by fhunleth** [comment]
Hi - I wanted to check on how things were going. I need to lock down the git/hex refs for ElixirConf training soon since I'm not going to be able to update things for the conference in the next couple weeks. Can I do anything to help get `scenic_driver_nerves_rpi` and this across the finish line? I'm on the Elixir-lang slack/email if anyone needs to debug live, but please send me .fw files so that I can reproduce. I'm assuming that things will work for me since they do already.

My only comment from briefly looking at this is that since RPi3 is mentioned so much here that having `nerves_init_gadget` default to `eth0` seems reasonable.

**Comment by boydm** [comment]
I have time to get to it later today..

**Comment by fhunleth** [comment]
@boydm Thanks for sending me the firmware. I looked through it and the root cause for your troubles was the port binary for `scenic_driver_nerves_rpi` wasn't included. Your .fw file was using `scenic_driver_nerves_rpi` v0.10.0 and when mix copied over the `priv` directory with the fonts, it erased the port binary. v0.10.1 doesn't do this since the `Makefile` is solely responsible for building and copying files to the `priv` dir. If you were to rebuild with v0.10.1 and no other changes, it should work for you.

**Comment by fhunleth** [comment]
Here's a diff that shows the contents of `scenic_driver_nerves_rpi-0.10.0` from your .fw file vs. what I have when I build. It's a little tedious to see, but `scenic_driver_nerves_rpi` is missing from yours.

image

**Comment by boydm** [comment]
Thank you @fhunleth.

That's much better. Totally me failing to update the deps correctly. There are days when this whole "software engineering" thing is a bit frustrating...

I'll get to the next PR you just added in a few minutes.

**Pull request merged**
