### PR TITLE
fix formatting issues

### PR DESCRIPTION
**Pull request by meox**
the purpose of this PR is to fix indentation and extra chars

### CODE REVIEW

**Comment by yordis** [comment]
Did you run `mix format`?

**Comment by meox** [comment]
no, I didn't

**Comment by boydm** [comment]
Ah. I see. The changes are in the templates. Formatter doesn't reach into there, but will create an app that needs formatting.

I'll take a better look at this when I'm not tired.

**Comment by boydm** [comment]
OK. Took the changes and did more so that now the generated app passes the formatter with no changes.

**Pull request merged**
