### PR TITLE
More updates to scenic.new.nerves

### PR DESCRIPTION
**Pull request by fhunleth**
This includes @axelson's changes from #40 and includes some additional ones:

* Configure RingLogger to get capture log messages
* Make eth0 the default so that running on a Raspberry Pi 3 requires no changes. I think this makes sense for Scenic, since the RPi 3 is mentioned a lot in the docs.
* Merge a few updates to the erlinit.config for consistency
* Add RPi3-specific next steps to the generator output.

This works well for me in my testing.

### CODE REVIEW

**Comment by boydm** [comment]
OK. This is merged. I'll push it to hex shortly.

Hey @fhunleth I was thinking it would be cool if scenic.new.nerves could just use nerves.new to set up the initial project, then delta in the scenic stuff. This project doesn't really add value in the way it sets up nerves and will always just be falling behind as you make changes on your side.

Would be nice if we could coordinate some way where I use your tool to set up the project and then just add in the Scenic stuff. That way the base setup moves ahead as you make your updates.

Thoughts?

**Comment by boydm** [comment]
This has been published to hex as v0.10.3

Thank you!

**Comment by fhunleth** [comment]
We have a similar situation with `mix new` and `mix nerves.new`. We regularly synchronize our new project generator based on whatever the latest is upstream Elixir and up-till-now Distillery. My process is very manual where I use `meld` or `Araxis` to diff generated projects and update our generator. I'm hesitant to automate since subtle things like `build_embedded` can cause a lot of headache due to different use cases between non-Nerves and Nerves users, and I like to make sure I understand each change. The Elixir 1.9 release support was particularly big. The feeling that I've gotten is that that one is likely the biggest change for a long time. As for Nerves, we'll be improving our networking support pretty significantly sometime within the next year and that will trickle down to the new project generator. Other than that, I'm hoping that everything else is really boring.

I'm not opposed to automation here or applying a diff with the Scenic bits. Whatever makes things easiest going forward. I wanted to fill you in on what I knew.

Mostly, though, thanks for posting the new versions to hex.pm! I think a couple updates to the training materials to bump versions and everything should be set with the Scenic/Nerves content!

**Comment by boydm** [comment]
If you need anything else in advance of ElixirConf, let me know and I'll get right on it.

Feels like there is a dependency graph for new style starters that hasn't really been thought through in the Elixir community. Maybe because it is just us?

Until we figure that out, we'll just have to shoot each other notes when we think we might be making breaking changes...

**Comment by axelson** [comment]
I'm excited for the changes here and in #40. One thing that could help would be adding a small script that will install the generator, create one project with nerves.new and one with scenic.nerves.new and then compare the output, that would be pretty light-weight.

**Comment by boydm** [comment]
@axelson And thank you again for the contributions here!

Really appreciated.

**Comment by axelson** [comment]
You're welcome. I'm glad to help!

**Pull request merged**
